In [59]:
import numpy as np
from pprint import pprint
import itertools

In [72]:
n = 6
# a = np.array(range(n ** 4)).reshape((n,) * 4)
a = np.load('rdm_ideal.npy')
print(a)

[[[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
   [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
   [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
   [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
   [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
   [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]]

  [[ 0.000e+00 -4.263e-02  1.351e-02  3.804e-02  3.210e-02 -3.246e-03]
   [ 4.263e-02  0.000e+00  8.360e-03  3.838e-02  4.895e-02 -9.649e-02]
   [-1.351e-02 -8.360e-03  0.000e+00  5.573e-03  1.789e-03  3.999e-02]
   [-3.804e-02 -3.838e-02 -5.573e-03  0.000e+00 -9.671e-03  6.039e-02]
   [-3.210e-02 -4.895e-02 -1.789e-03  9.671e-03  0.000e+00  3.952e-02]
   [ 3.246e-03  9.649e-02 -3.999e-02 -6.039e-02 -3.952e-02  0.000e+00]]

  [[ 0.000e+00  1.351e-02 -2.695e-02  8.588e-04  1.493e-02 -3.660e-02]
   [-1.351e-02  0.000e+00  1.968e-03 -2.508e-02 -3.165e-02  2.822e-02]
  

In [101]:
# non zero
def get_rdm_block(rdm, s, a1, a2, b1, b2):
    tmp = rdm[i*s:(i+1)*s, j*s:(j+1)*s, k*s:(k+1)*s, l*s:(l+1)*s]
    return tmp
s = n // 2
# print(s)
for i, j, k, l in itertools.product(range(2), repeat=4):
    print(i, j, k, l)
    tmp = a[i*s:(i+1)*s, j*s:(j+1)*s, k*s:(k+1)*s, l*s:(l+1)*s]
    print(tmp.reshape((s * s,) * 2))
    print(tmp.shape)
    # nonzeros, _ = np.nonzero(a[i*s:(i+1)*s, j*s:(j+1)*s, k*s:(k+1)*s, l*s:(l+1)*s])
    if np.all(np.isclose(tmp, 0.0) == True):
        print(tmp)
        print('')

0 0 0 0
[[ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.043  0.014  0.043  0.     0.008 -0.014 -0.008  0.   ]
 [ 0.     0.014 -0.027 -0.014  0.     0.002  0.027 -0.002  0.   ]
 [ 0.     0.043 -0.014 -0.043  0.    -0.008  0.014  0.008  0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.008  0.002 -0.008  0.    -0.003 -0.002  0.003  0.   ]
 [ 0.    -0.014  0.027  0.014  0.    -0.002 -0.027  0.002  0.   ]
 [ 0.    -0.008 -0.002  0.008  0.     0.003  0.002 -0.003  0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]
(3, 3, 3, 3)
0 0 0 1
[[ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.038  0.032 -0.003  0.038  0.049 -0.096  0.006  0.002  0.04 ]
 [ 0.001  0.015 -0.037 -0.025 -0.032  0.028  0.029  0.039 -0.071]
 [-0.038 -0.032  0.003 -0.038 -0.049  0.096 -0.006 -0.002 -0.04 ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [-0.01  -0.011  0.008 -0.005 -0.006  0.019 -0

0 0
(6, 6, 6, 6)
0 1
(6, 0, 6, 6)
[]

0 2
(6, 0, 6, 6)
[]

0 3
(6, 0, 6, 6)
[]

1 0
(0, 6, 6, 6)
[]

1 1
(0, 0, 6, 6)
[]

1 2
(0, 0, 6, 6)
[]

1 3
(0, 0, 6, 6)
[]

2 0
(0, 6, 6, 6)
[]

2 1
(0, 0, 6, 6)
[]

2 2
(0, 0, 6, 6)
[]

2 3
(0, 0, 6, 6)
[]

3 0
(0, 6, 6, 6)
[]

3 1
(0, 0, 6, 6)
[]

3 2
(0, 0, 6, 6)
[]

3 3
(0, 0, 6, 6)
[]



In [93]:
np.all(np.isclose(np.array([[0.0, 0.0], [0.0, 0.1]]), 0) == True)
# np.isclose(a, 0.0)

False

In [111]:

b = a.reshape((n * n,) * 2)
# print(b)

N = n * n // 4
print('N', N)
for i, j in itertools.product(range(4), repeat=2):
    # print(i, j)
    tmp = b[i*N:(i+1)*N, j*N:(j+1)*N]
    # print(tmp.reshape((s * s,) * 2))
    # print(tmp.shape)
    # nonzeros, _ = np.nonzero(a[i*s:(i+1)*s, j*s:(j+1)*s, k*s:(k+1)*s, l*s:(l+1)*s])
    if not np.all(np.isclose(tmp, 0.0) == True):
        print(tmp)
        print(i, j)

N 9
[[ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.043  0.014  0.038  0.032 -0.003  0.043  0.     0.008]
 [ 0.     0.014 -0.027  0.001  0.015 -0.037 -0.014  0.     0.002]
 [ 0.     0.038  0.001 -0.041 -0.043  0.024 -0.038  0.    -0.01 ]
 [ 0.     0.032  0.015 -0.043 -0.052  0.044 -0.032  0.    -0.011]
 [ 0.    -0.003 -0.037  0.024  0.044 -0.063  0.003  0.     0.008]
 [ 0.     0.043 -0.014 -0.038 -0.032  0.003 -0.043  0.    -0.008]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.008  0.002 -0.01  -0.011  0.008 -0.008  0.    -0.003]]
0 0
[[ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.038  0.049 -0.096 -0.014 -0.008  0.     0.006  0.002  0.04 ]
 [-0.025 -0.032  0.028  0.027 -0.002  0.     0.029  0.039 -0.071]
 [-0.027 -0.034  0.087 -0.001  0.01   0.    -0.023 -0.024 -0.002]
 [-0.015 -0.019  0.075 -0.015  0.011  0.    -0.039 -0.045  0.034]
 [-0.019 -0.023 -0.011  0.037 -0.008  0.     0.052  0.066 -0.094]
 

In [42]:
c = a.transpose([0, 1, 3, 2])
print(c)

[[[[   0    6   12   18   24   30]
   [   1    7   13   19   25   31]
   [   2    8   14   20   26   32]
   [   3    9   15   21   27   33]
   [   4   10   16   22   28   34]
   [   5   11   17   23   29   35]]

  [[  36   42   48   54   60   66]
   [  37   43   49   55   61   67]
   [  38   44   50   56   62   68]
   [  39   45   51   57   63   69]
   [  40   46   52   58   64   70]
   [  41   47   53   59   65   71]]

  [[  72   78   84   90   96  102]
   [  73   79   85   91   97  103]
   [  74   80   86   92   98  104]
   [  75   81   87   93   99  105]
   [  76   82   88   94  100  106]
   [  77   83   89   95  101  107]]

  [[ 108  114  120  126  132  138]
   [ 109  115  121  127  133  139]
   [ 110  116  122  128  134  140]
   [ 111  117  123  129  135  141]
   [ 112  118  124  130  136  142]
   [ 113  119  125  131  137  143]]

  [[ 144  150  156  162  168  174]
   [ 145  151  157  163  169  175]
   [ 146  152  158  164  170  176]
   [ 147  153  159  165  171  177]
   [ 148  15

In [43]:
d = c.reshape((n * n,) * 2)
print(d)

[[   0    6   12 ...   23   29   35]
 [  36   42   48 ...   59   65   71]
 [  72   78   84 ...   95  101  107]
 ...
 [1188 1194 1200 ... 1211 1217 1223]
 [1224 1230 1236 ... 1247 1253 1259]
 [1260 1266 1272 ... 1283 1289 1295]]


In [56]:
N = n * n // 4 # = 9
def perm(ids, N):
    rst = []
    for i in ids:
        k, l = divmod(i, N)
        new_idx = l * N + k
        rst.append(new_idx)
    return np.array(rst)
np.set_printoptions(precision=3)
print(a[0, 1, 1, 0])
print(c[0, 1, 0, 1])
print(b[N:2*N, N:2*N])
# print(b[19, N:2*N])
# print(d[19, 2*N:3*N])
# print(b[19, perm(range(0, n*n), N)])
print(b[12, :])
print(d[12, :])
print(d[N:2*N, 2*N:3*N])
print(d[N:2*N, N:2*N])
print(np.argwhere(b==223))
print(np.argwhere(d==223))
# print()

42
42
[[333 334 335 336 337 338 339 340 341]
 [369 370 371 372 373 374 375 376 377]
 [405 406 407 408 409 410 411 412 413]
 [441 442 443 444 445 446 447 448 449]
 [477 478 479 480 481 482 483 484 485]
 [513 514 515 516 517 518 519 520 521]
 [549 550 551 552 553 554 555 556 557]
 [585 586 587 588 589 590 591 592 593]
 [621 622 623 624 625 626 627 628 629]]
[432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467]
[432 438 444 450 456 462 433 439 445 451 457 463 434 440 446 452 458 464
 435 441 447 453 459 465 436 442 448 454 460 466 437 443 449 455 461 467]
[[327 333 339 345 351 357 328 334 340]
 [363 369 375 381 387 393 364 370 376]
 [399 405 411 417 423 429 400 406 412]
 [435 441 447 453 459 465 436 442 448]
 [471 477 483 489 495 501 472 478 484]
 [507 513 519 525 531 537 508 514 520]
 [543 549 555 561 567 573 544 550 556]
 [579 585 591 597 603 609 580 586 592]
 [615 621 627 633 639 645 616 622 62

In [48]:
idsb = range(0, n*n)
# idsd = []
def perm(ids, N):
    rst = []
    for i in ids:
        k, l = divmod(i, N)
        new_idx = l * N + k
        rst.append(new_idx)
    return np.array(rst)
print(perm(idsb, N))

[ 0  9 18 27 36 45 54 63 72  1 10 19 28 37 46 55 64 73  2 11 20 29 38 47
 56 65 74  3 12 21 30 39 48 57 66 75]
