In [1]:
import numpy as np

In [28]:
n = 6
a = np.array(range(n ** 4)).reshape((n,) * 4)
print(a)

[[[[   0    1    2    3    4    5]
   [   6    7    8    9   10   11]
   [  12   13   14   15   16   17]
   [  18   19   20   21   22   23]
   [  24   25   26   27   28   29]
   [  30   31   32   33   34   35]]

  [[  36   37   38   39   40   41]
   [  42   43   44   45   46   47]
   [  48   49   50   51   52   53]
   [  54   55   56   57   58   59]
   [  60   61   62   63   64   65]
   [  66   67   68   69   70   71]]

  [[  72   73   74   75   76   77]
   [  78   79   80   81   82   83]
   [  84   85   86   87   88   89]
   [  90   91   92   93   94   95]
   [  96   97   98   99  100  101]
   [ 102  103  104  105  106  107]]

  [[ 108  109  110  111  112  113]
   [ 114  115  116  117  118  119]
   [ 120  121  122  123  124  125]
   [ 126  127  128  129  130  131]
   [ 132  133  134  135  136  137]
   [ 138  139  140  141  142  143]]

  [[ 144  145  146  147  148  149]
   [ 150  151  152  153  154  155]
   [ 156  157  158  159  160  161]
   [ 162  163  164  165  166  167]
   [ 168  16

In [29]:

b = a.reshape((n * n,) * 2)
print(b)


[[   0    1    2 ...   33   34   35]
 [  36   37   38 ...   69   70   71]
 [  72   73   74 ...  105  106  107]
 ...
 [1188 1189 1190 ... 1221 1222 1223]
 [1224 1225 1226 ... 1257 1258 1259]
 [1260 1261 1262 ... 1293 1294 1295]]


In [30]:
c = a.transpose([1, 0, 2, 3])
print(c)

[[[[   0    1    2    3    4    5]
   [   6    7    8    9   10   11]
   [  12   13   14   15   16   17]
   [  18   19   20   21   22   23]
   [  24   25   26   27   28   29]
   [  30   31   32   33   34   35]]

  [[ 216  217  218  219  220  221]
   [ 222  223  224  225  226  227]
   [ 228  229  230  231  232  233]
   [ 234  235  236  237  238  239]
   [ 240  241  242  243  244  245]
   [ 246  247  248  249  250  251]]

  [[ 432  433  434  435  436  437]
   [ 438  439  440  441  442  443]
   [ 444  445  446  447  448  449]
   [ 450  451  452  453  454  455]
   [ 456  457  458  459  460  461]
   [ 462  463  464  465  466  467]]

  [[ 648  649  650  651  652  653]
   [ 654  655  656  657  658  659]
   [ 660  661  662  663  664  665]
   [ 666  667  668  669  670  671]
   [ 672  673  674  675  676  677]
   [ 678  679  680  681  682  683]]

  [[ 864  865  866  867  868  869]
   [ 870  871  872  873  874  875]
   [ 876  877  878  879  880  881]
   [ 882  883  884  885  886  887]
   [ 888  88

In [31]:
d = c.reshape((n * n,) * 2)
print(d)

[[   0    1    2 ...   33   34   35]
 [ 216  217  218 ...  249  250  251]
 [ 432  433  434 ...  465  466  467]
 ...
 [ 828  829  830 ...  861  862  863]
 [1044 1045 1046 ... 1077 1078 1079]
 [1260 1261 1262 ... 1293 1294 1295]]


In [36]:
print(a[1, 0, 1, 1])
print(c[0, 1, 1, 1])
print(np.argwhere(b==223))
print(np.argwhere(d==223))

223
223
[[6 7]]
[[1 7]]
